export default function categorias(type) {
  if (!type) return '';
  const map = {
    cafe: 'Café',
    restaurant: 'Restaurante',
    bar: 'Bar',
    pub: 'Pub',
    fast_food: 'Fast food',
    food_court: 'Praça de alimentação',
    biergarten: 'Biergarten',
    ice_cream: 'Sorveteria',
    bakery: 'Padaria',
    bank: 'Banco',
    atm: 'Caixa eletrônico',
    bureau_de_change: 'Casa de câmbio',
    pharmacy: 'Farmácia',
    clinic: 'Clínica',
    doctors: 'Consultório médico',
    dentist: 'Dentista',
    hospital: 'Hospital',
    veterinary: 'Clínica veterinária',
    school: 'Escola',
    kindergarten: 'Jardim de infância',
    college: 'Faculdade',
    university: 'Universidade',
    library: 'Biblioteca',
    music_school: 'Escola de música',
    arts_centre: 'Centro de artes',
    police: 'Polícia',
    fire_station: 'Corpo de bombeiros',
    post_office: 'Agência dos correios',
    townhall: 'Prefeitura',
    courthouse: 'Fórum',
    embassy: 'Embaixada',
    community_centre: 'Centro comunitário',
    theatre: 'Teatro',
    cinema: 'Cinema',
    nightclub: 'Boate',
    marketplace: 'Mercado público',
    place_of_worship: 'Templo',
    chapel: 'Capela',
    church: 'Igreja',
    mosque: 'Mesquita',
    synagogue: 'Sinagoga',
    fuel: 'Posto de combustível',
    car_wash: 'Lava a jato',
    charging_station: 'Eletroposto',
    parking: 'Estacionamento',
    bicycle_parking: 'Estacionamento de bicicletas',
    toilet: 'Banheiro público',
    drinking_water: 'Água potável',
    fountain: 'Chafariz',
    recycling: 'Ponto de reciclagem',
    waste_basket: 'Lixeira',
    shelter: 'Abrigo',
    bench: 'Banco',
    restaurant_bar: 'Restaurante/Bar',
    commercial: 'Comercial',

    supermarket: 'Supermercado',
    convenience: 'Loja de conveniência',
    bakery_shop: 'Padaria',
    butcher: 'Açougue',
    greengrocer: 'Hortifruti',
    confectionery: 'Confeitaria',
    clothes: 'Roupas',
    shoes: 'Calçados',
    florist: 'Florista',
    hairdresser: 'Cabeleireiro',
    beauty: 'Beleza/Estética',
    cosmetics: 'Cosméticos',
    chemist: 'Drogaria',
    bicycle: 'Bicicletas',
    car: 'Concessionária',
    car_repair: 'Oficina',
    electronics: 'Eletrônicos',
    mobile_phone: 'Celulares',
    computer: 'Informática',
    furniture: 'Móveis',
    department_store: 'Loja de departamentos',
    mall: 'Shopping',
    jewelry: 'Joalheria',
    optician: 'Ótica',
    sports: 'Artigos esportivos',
    books: 'Livraria',
    stationery: 'Papelaria',
    toys: 'Brinquedos',
    music: 'Música',
    video: 'Vídeo',
    pet: 'Pet shop',
    gift: 'Presentes',
    laundry: 'Lavanderia',
    dry_cleaning: 'Lavagem a seco',
    kiosk: 'Banca/Quiosque',
    pastry: 'Confeitaria',
    tea: 'Chá',
    coffee: 'Cafeteria',

    hotel: 'Hotel',
    motel: 'Motel',
    guest_house: 'Pousada',
    hostel: 'Hostel',
    apartment: 'Apartamento',
    chalet: 'Chalé',
    resort: 'Resort',
    camp_site: 'Camping',
    caravan_site: 'Área de trailers',
    information: 'Centro de informações turísticas',
    attraction: 'Atração turística',
    artwork: 'Obra de arte',
    museum: 'Museu',
    viewpoint: 'Mirante',
    theme_park: 'Parque temático',
    zoo: 'Zoológico',
    aquarium: 'Aquário',

    park: 'Parque',
    garden: 'Jardim',
    playground: 'Parquinho',
    pitch: 'Quadra/Campo',
    sports_centre: 'Centro esportivo',
    swimming_pool: 'Piscina',
    fitness_centre: 'Academia',
    stadium: 'Estádio',
    golf_course: 'Campo de golfe',
    dog_park: 'Parque para cães',

    company: 'Empresa',
    government: 'Órgão público',
    ngo: 'ONG',
    insurance: 'Seguradora',
    it: 'Empresa de TI',
    lawyer: 'Advocacia',
    accounting: 'Contabilidade',
    real_estate: 'Imobiliária',
    travel_agent: 'Agência de viagens',

    clinic_or_praxis: 'Clínica/Consultório',
    rehabilitation: 'Reabilitação',
    physiotherapist: 'Fisioterapia',
    pharmacy_healthcare: 'Farmácia',

    bus_stop: 'Ponto de ônibus',
    bus_station: 'Rodoviária',
    tram_stop: 'Parada de bonde',
    subway_entrance: 'Entrada de metrô',
    ferry_terminal: 'Terminal de balsa',
    railway_station: 'Estação de trem',
    airport: 'Aeroporto',
    aerodrome: 'Aeródromo',
    taxi: 'Ponto de táxi',
    bicycle_rental: 'Aluguel de bicicletas',
    car_rental: 'Aluguel de carros',
    car_sharing: 'Carro compartilhado',

    bed_and_breakfast: 'Cama e Café (B&B)',
    guesthouse: 'Pousada',

    bbq: 'Churrasco',
    brewery: 'Cervejaria',
    winery: 'Vinícola',
    tapas: 'Tapas',
    steak_house: 'Steakhouse',
    sushi: 'Sushi',
    noodle: 'Massa/Lamen',
    pizza: 'Pizzaria',
    burger: 'Hamburgueria',
    sandwich: 'Sanduíches',
    crepe: 'Creperia',
    pancake: 'Panquecas',

    arts_centre_variant: 'Centro de artes',
    cultural_centre: 'Centro cultural',
  };

  if (map[type]) return map[type];

  const pretty = type
    .split('_')
    .map(w => (w.length ? w[0].toUpperCase() + w.slice(1) : w))
    .join(' ');

  return pretty;
}
