name: Lint Frontend

on:
  push:
    branches: [main]
  pull_request: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      - name: Rodar lint
        run: yarn lint
